apiVersion: v1
kind: Service
metadata:
  name: kv-headless
  namespace: distributed-kv
spec:
  clusterIP: None
  selector:
    app: distributed-kv
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kv
  namespace: distributed-kv
spec:
  selector:
    app: distributed-kv
  ports:
    - port: 8080
      targetPort: 8080
